application:
  clients:
    admin:
      name: admin
      token: these-are-not-the-tokens-you-are-looking-for
    client1:
      name: client 1 name
      token: client1token
      # Maximum number of jobs a client can have in the processing queue
      process-limit: 2
      # Maximum number of jobs a client can have in total in its client queue
      job-limit: 100
      # Maximum number of jobs a user can have in the client queue
      user-client-limit: 1
      # Maximum number of jobs a user can have in their user queue
      user-job-limit: 20
    client2:
      name: client 2 name
      token: client2token
      process-limit: 2
      job-limit: 100
      user-client-limit: 1
      user-job-limit: 20